/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RavenHls {
        "autoplay": boolean;
        "src": string | null;
        "title": string;
    }
}
declare global {
    interface HTMLRavenHlsElement extends Components.RavenHls, HTMLStencilElement {
    }
    var HTMLRavenHlsElement: {
        prototype: HTMLRavenHlsElement;
        new (): HTMLRavenHlsElement;
    };
    interface HTMLElementTagNameMap {
        "raven-hls": HTMLRavenHlsElement;
    }
}
declare namespace LocalJSX {
    interface RavenHls {
        "autoplay"?: boolean;
        "src"?: string | null;
        "title"?: string;
    }
    interface IntrinsicElements {
        "raven-hls": RavenHls;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "raven-hls": LocalJSX.RavenHls & JSXBase.HTMLAttributes<HTMLRavenHlsElement>;
        }
    }
}
